[package]
name = "methods"
version = "0.1.0"
edition = "2021"

[build-dependencies]
risc0-build = { version = "^2.1.0" }

[package.metadata.risc0]
methods = ["keccak256", "sha256", "poseidon", "mimc", "ecdsa", "ecdsa_verify", "eddsa", "eddsa_verify", "fibonacci"]
