[package]
name = "fibonacciguest"
version = "0.1.0"
edition = "2024"

[workspace]

[dependencies]
risc0-zkvm = { version = "1.2.5", default-features = false, features = ['std', "getrandom"] }
hashing = { git = "https://github.com/anshalshukla/hashing" }