[package]
name = "ecdsaverifyguest"
version = "0.1.0"
edition = "2024"

[workspace]

[dependencies]
risc0-zkvm = { version = "^2.0.1", default-features = false, features = ['std', "getrandom"] }
hashing = { git = "https://github.com/anshalshukla/hashing" }
p256 = "0.13.2"